# Generated by Django 5.0.3 on 2024-03-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_category_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.category', verbose_name=''),
        ),
    ]
