# Generated by Django 5.0.3 on 2024-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_news_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Views count'),
        ),
    ]
